// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    var toggle_selected, toggle_sidebar;
    $(".content").hide();
    $(".mainPage").show();
    $(window).scroll(function() {
      var duration, offset;
      offset = 220;
      duration = 500;
      if ($(this).scrollTop() > offset) {
        $(".back-to-top").fadeIn(duration);
      } else {
        $(".back-to-top").fadeOut(duration);
      }
    });
    $(".back-to-top").click(function(e) {
      e.preventDefault();
      $("html, body").animate({
        scrollTop: 0
      }, 500);
      return false;
    });
    $("#menu-toggle").click(function(e) {
      e.preventDefault();
      $("#wrapper").toggleClass("active");
      return $(this).toggleClass("hidden");
    });
    $("#jp-left").click(function(e) {
      toggle_selected($(this));
      $("body").addClass("stardust");
      $(".jp").addClass("white");
      return $("#menu-toggle").addClass("white");
    });
    $(".page").click(function() {
      return toggle_selected($(this));
    });
    $(".inset").click(function() {
      return toggle_sidebar();
    });
    toggle_selected = function(btn) {
      var menu, page;
      toggle_sidebar();
      menu = $(".secondary-menu");
      menu.children().removeClass("selected");
      btn.children().addClass("selected");
      page = btn.data("page");
      $(".footer").fadeOut("normal");
      $("body").removeClass("stardust");
      $(".jp").removeClass("white");
      $("#menu-toggle").removeClass("white");
      return $(".currentPage").fadeOut("normal", function() {
        $(this).removeClass("currentPage");
        $(".footer").fadeIn("slow");
        return $("." + page).fadeIn("normal", function() {
          return $(this).addClass("currentPage");
        });
      });
    };
    return toggle_sidebar = function() {
      if ($("#wrapper").hasClass("active")) {
        $("#wrapper").toggleClass("active");
        return $("#menu-toggle").toggleClass("hidden");
      }
    };
  });

}).call(this);
