// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    var toggle_selected, toggle_sidebar;
    $("#menu-toggle").click(function(e) {
      e.preventDefault();
      $("#wrapper").toggleClass("active");
      return $(this).toggleClass("hidden");
    });
    $("#jp-left").click(function(e) {
      e.preventDefault();
      return toggle_sidebar();
    });
    $("#profile-btn").click(function() {
      toggle_selected($(this));
      return $(".profile").removeClass("hidden");
    });
    $("#resume-btn").click(function() {
      toggle_selected($(this));
      return $(".resume").removeClass("hidden");
    });
    $("#smth-btn").click(function() {
      toggle_selected($(this));
      return $(".work").removeClass("hidden");
    });
    toggle_selected = function(btn) {
      var contents, menu;
      toggle_sidebar();
      menu = $(".secondary-menu");
      menu.children().removeClass("selected");
      btn.children().addClass("selected");
      contents = $(".page-content");
      return contents.children().addClass("hidden");
    };
    return toggle_sidebar = function() {
      if ($("#wrapper").hasClass("active")) {
        $("#wrapper").toggleClass("active");
        return $("#menu-toggle").toggleClass("hidden");
      }
    };
  });

}).call(this);
